spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
routes:
  public: /app/login,/app/registro
  authenticated: /app/index
  byrole: /app/usuarios:ROLE_ADMIN,/app/usuarios/listado/:ROLE_ADMIN